---
- hosts: localhost
  become: true

  tasks:
  - name: create docker image using file
    command: docker build -t dummy-pdf-or-png:latest .
    args:
      chdir: /opt/k8s-lab/hiring-assignments/sre/dummy-pdf-or-png/
      
  - name: create tag to image
    command: docker tag dummy-pdf-or-png vivekk480/dummy-pdf-or-png

  - name: push image on to dockerhub
    command: docker push vivekk480/dummy-pdf-or-png

  - name: remove docker images form ansible server
    command: docker rmi dummy-pdf-or-png:latest vivekk480/dummy-pdf-or-png
    ignore_errors: yes
