apiVersion: v1
kind: Service
metadata:
  name: visma-service
  labels:
    app: visma-devops-project
spec:
  selector:
    app: visma-devops-project
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000
