apiVersion: v1
kind: Service
metadata:
  name: visma-service
  labels:
    app: visma-devops-project
spec:
  selector:
    app: visma-devops-project
  type: LoadBalancer
  ports:
    - name: actuator
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31200
