apiVersion: apps/v1
kind: Deployment
metadata:
  name: visma-deployment
spec:
  selector:
    matchLabels:
      app: visma-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  
  template:
    metadata: 
      labels:
        app: visma-devops-project
    spec:
      containers:
      - name: visma-devops-project
        image: vivekk480/dummy-pdf-or-png
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 8081
          name: healthhttp
          protocol: TCP

        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        readinessProbe:
          failureThreshold: 15
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 20
