// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DocumentSummarizerClient is the client API for DocumentSummarizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentSummarizerClient interface {
	SummarizeDocument(ctx context.Context, in *SummarizeDocumentRequest, opts ...grpc.CallOption) (*SummarizeDocumentReply, error)
}

type documentSummarizerClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentSummarizerClient(cc grpc.ClientConnInterface) DocumentSummarizerClient {
	return &documentSummarizerClient{cc}
}

func (c *documentSummarizerClient) SummarizeDocument(ctx context.Context, in *SummarizeDocumentRequest, opts ...grpc.CallOption) (*SummarizeDocumentReply, error) {
	out := new(SummarizeDocumentReply)
	err := c.cc.Invoke(ctx, "/statistics.DocumentSummarizer/SummarizeDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentSummarizerServer is the server API for DocumentSummarizer service.
// All implementations must embed UnimplementedDocumentSummarizerServer
// for forward compatibility
type DocumentSummarizerServer interface {
	SummarizeDocument(context.Context, *SummarizeDocumentRequest) (*SummarizeDocumentReply, error)
	mustEmbedUnimplementedDocumentSummarizerServer()
}

// UnimplementedDocumentSummarizerServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentSummarizerServer struct {
}

func (UnimplementedDocumentSummarizerServer) SummarizeDocument(context.Context, *SummarizeDocumentRequest) (*SummarizeDocumentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SummarizeDocument not implemented")
}
func (UnimplementedDocumentSummarizerServer) mustEmbedUnimplementedDocumentSummarizerServer() {}

// UnsafeDocumentSummarizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentSummarizerServer will
// result in compilation errors.
type UnsafeDocumentSummarizerServer interface {
	mustEmbedUnimplementedDocumentSummarizerServer()
}

func RegisterDocumentSummarizerServer(s grpc.ServiceRegistrar, srv DocumentSummarizerServer) {
	s.RegisterService(&_DocumentSummarizer_serviceDesc, srv)
}

func _DocumentSummarizer_SummarizeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentSummarizerServer).SummarizeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statistics.DocumentSummarizer/SummarizeDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentSummarizerServer).SummarizeDocument(ctx, req.(*SummarizeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocumentSummarizer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.DocumentSummarizer",
	HandlerType: (*DocumentSummarizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SummarizeDocument",
			Handler:    _DocumentSummarizer_SummarizeDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
